namespace SoFi.Api.Domain;

/// <summary>
/// A product brand (Apple, TP-Link, …).
/// Mirrors what used to be the Drizzle `brand` table — same columns, same
/// snake_case names in SQL (handled by EFCore.NamingConventions).
/// </summary>
public class Brand
{
    /// <summary>UUID generated in application code (crypto.randomUUID() in TS, Guid here).</summary>
    public string Id { get; set; } = default!;

    public string Name { get; set; } = default!;

    /// <summary>URL-friendly name ("tp-link") used in links instead of the id.</summary>
    public string Slug { get; set; } = default!;

    public DateTime CreatedAt { get; set; }

    // Navigation property: EF Core fills this when we .Include(b => b.Products).
    public ICollection<Product> Products { get; set; } = new List<Product>();
}

/// <summary>A product category: laptop, phone, router… Slugs match placeholder SVGs.</summary>
public class Category
{
    public string Id { get; set; } = default!;
    public string Name { get; set; } = default!;
    public string Slug { get; set; } = default!;
    public DateTime CreatedAt { get; set; }

    public ICollection<Product> Products { get; set; } = new List<Product>();
}

/// <summary>
/// The central table of the shop.
///
 /// Two conventions carried over from the TypeScript version:
 /// - Money is stored as WHOLE CENTS in ints (no floating point rounding bugs).
 /// - Ids are text UUIDs generated by the app, not database-generated — this
 ///   lets services build related rows before saving anything.
/// </summary>
public class Product
{
    public string Id { get; set; } = default!;
    public string Name { get; set; } = default!;
    public string Slug { get; set; } = default!;
    public string Description { get; set; } = string.Empty;

    /// <summary>Price in cents: $1,099.00 → 109900.</summary>
    public int PriceCents { get; set; }

    public int Stock { get; set; }

    public string? ImageUrl { get; set; }

    /// <summary>
    /// Flexible spec key/values ("RAM" → "16 GB"). Npgsql maps a Dictionary to
    /// a PostgreSQL `jsonb` column automatically — no converter needed.
    /// </summary>
    public Dictionary<string, string> Specs { get; set; } = new();

    /// <summary>1 = shown on the homepage (kept as int for parity with old data/seed logic).</summary>
    public int Featured { get; set; }

    // Foreign keys — EF turns these into real FK constraints automatically.
    public string BrandId { get; set; } = default!;
    public string CategoryId { get; set; } = default!;

    // Navigation properties
    public Brand Brand { get; set; } = default!;
    public Category Category { get; set; } = default!;

    public DateTime CreatedAt { get; set; }
}
